import { ComponentConfig } from "@/types/components";
import {
  Cpu,
  Lightbulb,
  Waves,
  Thermometer,
  Ruler,
  Eye,
  Sun,
  Radio,
  Wind,
  Droplets,
  Sprout,
  Compass,
  MapPin,
  Monitor,
  Grid3x3,
  Binary,
  Tv,
  RotateCw,
  Fan,
  Repeat,
  Volume2,
  ToggleLeft,
  Circle,
  Gauge,
  Hash,
  Palette,
  Zap,
  Activity,
  Bluetooth,
  Wifi,
  Signal,
  CreditCard,
} from "lucide-react";

export const COMPONENT_DATA: ComponentConfig[] = [
  // ===== BOARDS =====
  {
    id: "arduino-uno",
    name: "Arduino UNO",
    category: "boards",
    description: "ATmega328P microcontroller board",
    pins: [
      // DIGITAL pins D0-D13 - Top-right black header
      // Original image: 794×581, Display: 340×250 (scale: 0.428×0.430)
      // Use pin-coordinate-picker.html to get exact coordinates!
      { id: "d0", label: "D0", x: 307, y: 22, type: "digital" },
      { id: "d1", label: "D1", x: 296, y: 22, type: "digital" },
      { id: "d2", label: "D2", x: 285, y: 22, type: "digital" },
      { id: "d3", label: "D3", x: 274, y: 22, type: "digital" },
      { id: "d4", label: "D4", x: 264, y: 22, type: "digital" },
      { id: "d5", label: "D5", x: 253, y: 22, type: "digital" },
      { id: "d6", label: "D6", x: 242, y: 22, type: "digital" },
      { id: "d7", label: "D7", x: 231, y: 22, type: "digital" },
      { id: "d8", label: "D8", x: 214, y: 22, type: "digital" },
      { id: "d9", label: "D9", x: 203, y: 22, type: "digital" },
      { id: "d10", label: "D10", x: 192, y: 22, type: "digital" },
      { id: "d11", label: "D11", x: 182, y: 22, type: "digital" },
      { id: "d12", label: "D12", x: 172, y: 22, type: "digital" },
      { id: "d13", label: "D13", x: 161, y: 22, type: "digital" },
      { id: "gnd1", label: "GND", x: 150, y: 23, type: "ground" },
      { id: "aref", label: "AREF", x: 139, y: 22, type: "analog" },


      // POWER pins - Left black header (dual row)
      { id: "ioref", label: "IOREF", x: 167, y: 226, type: "power" },
      { id: "reset", label: "RESET", x: 177, y: 227, type: "power" },
      { id: "3v3", label: "3.3V", x: 188, y: 227, type: "power" },
      { id: "5v", label: "5V", x: 199, y: 227, type: "power" },
      { id: "gnd2", label: "GND", x: 210, y: 227, type: "ground" },
      { id: "gnd3", label: "GND", x: 221, y: 227, type: "ground" },
      { id: "vin", label: "Vin", x: 231, y: 227, type: "power" },

      // ANALOG IN pins A0-A5 - Bottom-right black header (single row)
      { id: "a0", label: "A0", x: 253, y: 227, type: "analog" },
      { id: "a1", label: "A1", x: 264, y: 227, type: "analog" },
      { id: "a2", label: "A2", x: 275, y: 227, type: "analog" },
      { id: "a3", label: "A3", x: 284, y: 227, type: "analog" },
      { id: "a4", label: "A4", x: 295, y: 227, type: "analog" },
      { id: "a5", label: "A5", x: 306, y: 226, type: "analog" },
    ],
    width: 340,
    height: 250,
    imagePath: "/arduino-uno.png",
  },

  // ===== SENSORS =====
  {
    id: "dht11",
    name: "DHT11",
    category: "sensors",
    description: "Temperature & Humidity Sensor",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "data", label: "DATA", x: 0, y: 15, type: "data" },
      { id: "gnd", label: "GND", x: 0, y: 30, type: "ground" },
    ],
    width: 60,
    height: 80,
    imagePath: "/components/dht11.svg",
  },
  {
    id: "dht22",
    name: "DHT22",
    category: "sensors",
    description: "High precision Temperature & Humidity",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "data", label: "DATA", x: 0, y: 15, type: "data" },
      { id: "gnd", label: "GND", x: 0, y: 30, type: "ground" },
    ],
    width: 60,
    height: 80,
    imagePath: "/components/dht22.svg",
  },
  {
    id: "hc-sr04",
    name: "HC-SR04",
    category: "sensors",
    description: "Ultrasonic Distance Sensor",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "trig", label: "TRIG", x: 0, y: 15, type: "digital" },
      { id: "echo", label: "ECHO", x: 0, y: 30, type: "digital" },
      { id: "gnd", label: "GND", x: 0, y: 45, type: "ground" },
    ],
    width: 80,
    height: 60,
    imagePath: "/components/hc-sr04.svg",
  },
  {
    id: "pir",
    name: "PIR Sensor",
    category: "sensors",
    description: "Motion Detection Sensor",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "out", label: "OUT", x: 0, y: 15, type: "digital" },
      { id: "gnd", label: "GND", x: 0, y: 30, type: "ground" },
    ],
    width: 70,
    height: 70,
    imagePath: "/components/pir.svg",
  },
  {
    id: "ldr",
    name: "LDR",
    category: "sensors",
    description: "Light Dependent Resistor",
    pins: [
      { id: "pin1", label: "PIN1", x: 0, y: 0, type: "analog" },
      { id: "pin2", label: "PIN2", x: 0, y: 40, type: "analog" },
    ],
    width: 40,
    height: 50,
    imagePath: "/components/ldr.svg",
  },
  {
    id: "ir-sensor",
    name: "IR Sensor",
    category: "sensors",
    description: "Infrared Obstacle Detection",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "out", label: "OUT", x: 0, y: 15, type: "digital" },
      { id: "gnd", label: "GND", x: 0, y: 30, type: "ground" },
    ],
    width: 60,
    height: 50,
    imagePath: "/components/ir-sensor.svg",
  },
  {
    id: "mq2",
    name: "MQ-2",
    category: "sensors",
    description: "Gas & Smoke Sensor",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "dout", label: "DOUT", x: 0, y: 15, type: "digital" },
      { id: "aout", label: "AOUT", x: 0, y: 30, type: "analog" },
      { id: "gnd", label: "GND", x: 0, y: 45, type: "ground" },
    ],
    width: 60,
    height: 70,
    imagePath: "/components/mq2.svg",
  },
  {
    id: "sound-sensor",
    name: "Sound Sensor",
    category: "sensors",
    description: "Sound Detection Module",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "dout", label: "DOUT", x: 0, y: 15, type: "digital" },
      { id: "aout", label: "AOUT", x: 0, y: 30, type: "analog" },
      { id: "gnd", label: "GND", x: 0, y: 45, type: "ground" },
    ],
    width: 60,
    height: 60,
    imagePath: "/components/sound-sensor.svg",
  },
  {
    id: "rain-sensor",
    name: "Rain Sensor",
    category: "sensors",
    description: "Rain Detection Module",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "dout", label: "DOUT", x: 0, y: 15, type: "digital" },
      { id: "aout", label: "AOUT", x: 0, y: 30, type: "analog" },
      { id: "gnd", label: "GND", x: 0, y: 45, type: "ground" },
    ],
    width: 70,
    height: 50,
    imagePath: "/components/rain-sensor.svg",
  },
  {
    id: "soil-moisture",
    name: "Soil Moisture",
    category: "sensors",
    description: "Soil Moisture Sensor",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "dout", label: "DOUT", x: 0, y: 15, type: "digital" },
      { id: "aout", label: "AOUT", x: 0, y: 30, type: "analog" },
      { id: "gnd", label: "GND", x: 0, y: 45, type: "ground" },
    ],
    width: 60,
    height: 80,
    imagePath: "/components/soil-moisture.svg",
  },
  {
    id: "mpu6050",
    name: "MPU6050",
    category: "sensors",
    description: "Gyroscope & Accelerometer",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 15, type: "ground" },
      { id: "scl", label: "SCL", x: 0, y: 30, type: "data" },
      { id: "sda", label: "SDA", x: 0, y: 45, type: "data" },
    ],
    width: 70,
    height: 60,
    imagePath: "/components/mpu6050.svg",
  },
  {
    id: "gps-neo6m",
    name: "GPS NEO-6M",
    category: "sensors",
    description: "GPS Module",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "tx", label: "TX", x: 0, y: 15, type: "data" },
      { id: "rx", label: "RX", x: 0, y: 30, type: "data" },
      { id: "gnd", label: "GND", x: 0, y: 45, type: "ground" },
    ],
    width: 80,
    height: 80,
    imagePath: "/components/gps-neo6m.svg",
  },

  // ===== DISPLAYS =====
  {
    id: "lcd-16x2",
    name: "LCD 16x2",
    category: "displays",
    description: "16x2 Character LCD Display",
    pins: [
      { id: "vss", label: "VSS", x: 0, y: 0, type: "ground" },
      { id: "vdd", label: "VDD", x: 0, y: 10, type: "power" },
      { id: "rs", label: "RS", x: 0, y: 20, type: "digital" },
      { id: "rw", label: "RW", x: 0, y: 30, type: "digital" },
      { id: "e", label: "E", x: 0, y: 40, type: "digital" },
      { id: "d4", label: "D4", x: 0, y: 50, type: "data" },
      { id: "d5", label: "D5", x: 0, y: 60, type: "data" },
      { id: "d6", label: "D6", x: 0, y: 70, type: "data" },
      { id: "d7", label: "D7", x: 0, y: 80, type: "data" },
    ],
    width: 120,
    height: 60,
    imagePath: "/components/lcd-16x2.svg",
  },
  {
    id: "oled-128x64",
    name: "OLED 128x64",
    category: "displays",
    description: "OLED Display I2C",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 15, type: "ground" },
      { id: "scl", label: "SCL", x: 0, y: 30, type: "data" },
      { id: "sda", label: "SDA", x: 0, y: 45, type: "data" },
    ],
    width: 90,
    height: 70,
    imagePath: "/components/oled-128x64.svg",
  },
  {
    id: "7segment",
    name: "7-Segment Display",
    category: "displays",
    description: "Single Digit 7-Segment",
    pins: [
      { id: "a", label: "A", x: 0, y: 0, type: "digital" },
      { id: "b", label: "B", x: 0, y: 10, type: "digital" },
      { id: "c", label: "C", x: 0, y: 20, type: "digital" },
      { id: "d", label: "D", x: 0, y: 30, type: "digital" },
      { id: "e", label: "E", x: 0, y: 40, type: "digital" },
      { id: "f", label: "F", x: 0, y: 50, type: "digital" },
      { id: "g", label: "G", x: 0, y: 60, type: "digital" },
      { id: "com", label: "COM", x: 0, y: 70, type: "ground" },
    ],
    width: 60,
    height: 90,
    imagePath: "/components/7segment.svg",
  },
  {
    id: "led-matrix-8x8",
    name: "LED Matrix 8x8",
    category: "displays",
    description: "8x8 LED Matrix Display",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 15, type: "ground" },
      { id: "din", label: "DIN", x: 0, y: 30, type: "data" },
      { id: "cs", label: "CS", x: 0, y: 45, type: "data" },
      { id: "clk", label: "CLK", x: 0, y: 60, type: "data" },
    ],
    width: 80,
    height: 80,
    imagePath: "/components/led-matrix-8x8.svg",
  },
  {
    id: "tft-display",
    name: "TFT Display",
    category: "displays",
    description: '2.4" TFT LCD Display',
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 15, type: "ground" },
      { id: "cs", label: "CS", x: 0, y: 30, type: "data" },
      { id: "reset", label: "RESET", x: 0, y: 45, type: "digital" },
      { id: "dc", label: "DC", x: 0, y: 60, type: "data" },
      { id: "mosi", label: "MOSI", x: 0, y: 75, type: "data" },
      { id: "sck", label: "SCK", x: 0, y: 90, type: "data" },
      { id: "led", label: "LED", x: 0, y: 105, type: "power" },
    ],
    width: 100,
    height: 130,
    imagePath: "/components/tft-display.svg",
  },

  // ===== ACTUATORS =====
  {
    id: "servo-sg90",
    name: "Servo SG90",
    category: "actuators",
    description: "9g Micro Servo Motor",
    pins: [
      { id: "signal", label: "SIGNAL", x: 0, y: 0, type: "digital" },
      { id: "vcc", label: "VCC", x: 0, y: 15, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 30, type: "ground" },
    ],
    width: 70,
    height: 50,
    imagePath: "/components/servo-sg90.svg",
  },
  {
    id: "dc-motor",
    name: "DC Motor",
    category: "actuators",
    description: "DC Motor with Driver",
    pins: [
      { id: "in1", label: "IN1", x: 0, y: 0, type: "digital" },
      { id: "in2", label: "IN2", x: 0, y: 15, type: "digital" },
      { id: "vcc", label: "VCC", x: 0, y: 30, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 45, type: "ground" },
    ],
    width: 80,
    height: 60,
    imagePath: "/components/dc-motor.svg",
  },
  {
    id: "stepper-motor",
    name: "Stepper Motor",
    category: "actuators",
    description: "28BYJ-48 Stepper Motor",
    pins: [
      { id: "in1", label: "IN1", x: 0, y: 0, type: "digital" },
      { id: "in2", label: "IN2", x: 0, y: 15, type: "digital" },
      { id: "in3", label: "IN3", x: 0, y: 30, type: "digital" },
      { id: "in4", label: "IN4", x: 0, y: 45, type: "digital" },
      { id: "vcc", label: "VCC", x: 0, y: 60, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 75, type: "ground" },
    ],
    width: 80,
    height: 70,
    imagePath: "/components/stepper-motor.svg",
  },
  {
    id: "buzzer",
    name: "Buzzer",
    category: "actuators",
    description: "Active/Passive Buzzer",
    pins: [
      { id: "positive", label: "+", x: 0, y: 0, type: "digital" },
      { id: "negative", label: "-", x: 0, y: 20, type: "ground" },
    ],
    width: 40,
    height: 40,
    imagePath: "/components/buzzer.svg",
  },
  {
    id: "relay",
    name: "Relay Module",
    category: "actuators",
    description: "5V Relay Module",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "in", label: "IN", x: 0, y: 15, type: "digital" },
      { id: "gnd", label: "GND", x: 0, y: 30, type: "ground" },
    ],
    width: 70,
    height: 60,
    imagePath: "/components/relay.svg",
  },

  // ===== COMMUNICATION =====
  {
    id: "hc05",
    name: "HC-05",
    category: "communication",
    description: "Bluetooth Module",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 15, type: "ground" },
      { id: "tx", label: "TX", x: 0, y: 30, type: "data" },
      { id: "rx", label: "RX", x: 0, y: 45, type: "data" },
    ],
    width: 70,
    height: 50,
    imagePath: "/components/hc05.svg",
  },
  {
    id: "esp8266",
    name: "ESP8266",
    category: "communication",
    description: "WiFi Module",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 15, type: "ground" },
      { id: "tx", label: "TX", x: 0, y: 30, type: "data" },
      { id: "rx", label: "RX", x: 0, y: 45, type: "data" },
      { id: "ch_pd", label: "CH_PD", x: 0, y: 60, type: "digital" },
      { id: "rst", label: "RST", x: 0, y: 75, type: "digital" },
    ],
    width: 80,
    height: 60,
    imagePath: "/components/esp8266.svg",
  },
  {
    id: "nrf24l01",
    name: "NRF24L01",
    category: "communication",
    description: "RF Wireless Module",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "gnd", label: "GND", x: 0, y: 15, type: "ground" },
      { id: "ce", label: "CE", x: 0, y: 30, type: "digital" },
      { id: "csn", label: "CSN", x: 0, y: 45, type: "digital" },
      { id: "sck", label: "SCK", x: 0, y: 60, type: "data" },
      { id: "mosi", label: "MOSI", x: 0, y: 75, type: "data" },
      { id: "miso", label: "MISO", x: 0, y: 90, type: "data" },
    ],
    width: 70,
    height: 60,
    imagePath: "/components/nrf24l01.svg",
  },
  {
    id: "rfid-rc522",
    name: "RFID RC522",
    category: "communication",
    description: "RFID Reader Module",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "rst", label: "RST", x: 0, y: 15, type: "digital" },
      { id: "gnd", label: "GND", x: 0, y: 30, type: "ground" },
      { id: "miso", label: "MISO", x: 0, y: 45, type: "data" },
      { id: "mosi", label: "MOSI", x: 0, y: 60, type: "data" },
      { id: "sck", label: "SCK", x: 0, y: 75, type: "data" },
      { id: "sda", label: "SDA", x: 0, y: 90, type: "data" },
    ],
    width: 90,
    height: 70,
    imagePath: "/components/rfid-rc522.svg",
  },

  // ===== BASIC COMPONENTS =====
  {
    id: "led-red",
    name: "LED (Red)",
    category: "basic",
    description: "Red Light Emitting Diode",
    pins: [
      { id: "anode", label: "+", x: 15, y: 5, type: "digital" },
      { id: "cathode", label: "-", x: 15, y: 45, type: "ground" },
    ],
    width: 30,
    height: 50,
    imagePath: "/components/led-red.svg",
    defaultProps: { color: "red" },
  },
  {
    id: "led-green",
    name: "LED (Green)",
    category: "basic",
    description: "Green Light Emitting Diode",
    pins: [
      { id: "anode", label: "+", x: 15, y: 5, type: "digital" },
      { id: "cathode", label: "-", x: 15, y: 45, type: "ground" },
    ],
    width: 30,
    height: 50,
    imagePath: "/components/led-green.svg",
    defaultProps: { color: "green" },
  },
  {
    id: "led-blue",
    name: "LED (Blue)",
    category: "basic",
    description: "Blue Light Emitting Diode",
    pins: [
      { id: "anode", label: "+", x: 15, y: 5, type: "digital" },
      { id: "cathode", label: "-", x: 15, y: 45, type: "ground" },
    ],
    width: 30,
    height: 50,
    imagePath: "/components/led-blue.svg",
    defaultProps: { color: "blue" },
  },
  {
    id: "rgb-led",
    name: "RGB LED",
    category: "basic",
    description: "RGB LED Common Cathode",
    pins: [
      { id: "r", label: "R", x: 0, y: 0, type: "digital" },
      { id: "gnd", label: "GND", x: 0, y: 15, type: "ground" },
      { id: "g", label: "G", x: 0, y: 30, type: "digital" },
      { id: "b", label: "B", x: 0, y: 45, type: "digital" },
    ],
    width: 40,
    height: 60,
    imagePath: "/components/rgb-led.svg",
  },
  {
    id: "push-button",
    name: "Push Button",
    category: "basic",
    description: "Tactile Push Button",
    pins: [
      { id: "pin1", label: "1", x: 0, y: 0, type: "digital" },
      { id: "pin2", label: "2", x: 40, y: 0, type: "digital" },
      { id: "pin3", label: "3", x: 0, y: 40, type: "digital" },
      { id: "pin4", label: "4", x: 40, y: 40, type: "digital" },
    ],
    width: 50,
    height: 50,
    imagePath: "/components/push-button.svg",
  },
  {
    id: "potentiometer",
    name: "Potentiometer",
    category: "basic",
    description: "10K Potentiometer",
    pins: [
      { id: "vcc", label: "VCC", x: 0, y: 0, type: "power" },
      { id: "wiper", label: "OUT", x: 0, y: 20, type: "analog" },
      { id: "gnd", label: "GND", x: 0, y: 40, type: "ground" },
    ],
    width: 50,
    height: 60,
    imagePath: "/components/potentiometer.svg",
  },
  {
    id: "keypad-4x4",
    name: "Keypad 4x4",
    category: "basic",
    description: "4x4 Matrix Keypad",
    pins: [
      { id: "r1", label: "R1", x: 0, y: 0, type: "digital" },
      { id: "r2", label: "R2", x: 0, y: 12, type: "digital" },
      { id: "r3", label: "R3", x: 0, y: 24, type: "digital" },
      { id: "r4", label: "R4", x: 0, y: 36, type: "digital" },
      { id: "c1", label: "C1", x: 0, y: 48, type: "digital" },
      { id: "c2", label: "C2", x: 0, y: 60, type: "digital" },
      { id: "c3", label: "C3", x: 0, y: 72, type: "digital" },
      { id: "c4", label: "C4", x: 0, y: 84, type: "digital" },
    ],
    width: 80,
    height: 100,
    imagePath: "/components/keypad-4x4.svg",
  },
  {
    id: "resistor-220",
    name: "Resistor 220Ω",
    category: "basic",
    description: "220 Ohm Resistor",
    pins: [
      { id: "pin1", label: "1", x: 0, y: 15, type: "analog" },
      { id: "pin2", label: "2", x: 80, y: 15, type: "analog" },
    ],
    width: 80,
    height: 30,
    imagePath: "/components/resistor-220.svg",
  },
  {
    id: "resistor-1k",
    name: "Resistor 1KΩ",
    category: "basic",
    description: "1K Ohm Resistor",
    pins: [
      { id: "pin1", label: "1", x: 0, y: 15, type: "analog" },
      { id: "pin2", label: "2", x: 80, y: 15, type: "analog" },
    ],
    width: 80,
    height: 30,
    imagePath: "/components/resistor-1k.svg",
  },
  {
    id: "resistor-10k",
    name: "Resistor 10KΩ",
    category: "basic",
    description: "10K Ohm Resistor",
    pins: [
      { id: "pin1", label: "1", x: 0, y: 15, type: "analog" },
      { id: "pin2", label: "2", x: 80, y: 15, type: "analog" },
    ],
    width: 80,
    height: 30,
    imagePath: "/components/resistor-10k.svg",
  },
  {
    id: "capacitor",
    name: "Capacitor",
    category: "basic",
    description: "Electrolytic Capacitor",
    pins: [
      { id: "positive", label: "+", x: 0, y: 0, type: "analog" },
      { id: "negative", label: "-", x: 0, y: 40, type: "ground" },
    ],
    width: 40,
    height: 50,
    imagePath: "/components/capacitor.svg",
  },
  {
    id: "transistor-npn",
    name: "Transistor NPN",
    category: "basic",
    description: "NPN Transistor (2N2222)",
    pins: [
      { id: "emitter", label: "E", x: 0, y: 0, type: "analog" },
      { id: "base", label: "B", x: 0, y: 20, type: "digital" },
      { id: "collector", label: "C", x: 0, y: 40, type: "analog" },
    ],
    width: 40,
    height: 50,
    imagePath: "/components/transistor-npn.svg",
  },
];

// Helper function to get icon for component
export const getComponentIcon = (componentId: string) => {
  const iconMap: Record<string, React.ComponentType> = {
    "arduino-uno": Cpu,
    dht11: Thermometer,
    dht22: Thermometer,
    "hc-sr04": Ruler,
    pir: Eye,
    ldr: Sun,
    "ir-sensor": Radio,
    mq2: Wind,
    "sound-sensor": Volume2,
    "rain-sensor": Droplets,
    "soil-moisture": Sprout,
    mpu6050: Compass,
    "gps-neo6m": MapPin,
    "lcd-16x2": Monitor,
    "oled-128x64": Monitor,
    "7segment": Binary,
    "led-matrix-8x8": Grid3x3,
    "tft-display": Tv,
    "servo-sg90": RotateCw,
    "dc-motor": Fan,
    "stepper-motor": Repeat,
    buzzer: Volume2,
    relay: ToggleLeft,
    hc05: Bluetooth,
    esp8266: Wifi,
    nrf24l01: Signal,
    "rfid-rc522": CreditCard,
    "led-red": Lightbulb,
    "led-green": Lightbulb,
    "led-blue": Lightbulb,
    "rgb-led": Palette,
    "push-button": Circle,
    potentiometer: Gauge,
    "keypad-4x4": Hash,
    "resistor-220": Waves,
    "resistor-1k": Waves,
    "resistor-10k": Waves,
    capacitor: Zap,
    "transistor-npn": Activity,
  };
  return iconMap[componentId] || Circle;
};
